<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="Dahomey.Cbor" Version="1.16.1" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="9.0.9" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FuncionesGeotimeLib\GeotimeFuncionesLib.csproj" />
    <ProjectReference Include="..\GeotimeModelsLib\GeotimeModelsLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="JtSegEncrypta">
      <HintPath>..\..\..\..\JtSegEncrypta\JtSegEncrypta.dll</HintPath>
    </Reference>
    <Reference Include="LibEncripta">
      <HintPath>..\..\..\..\LibEncripta\LibEncripta\bin\Release\net6.0\LibEncripta.dll</HintPath>
    </Reference>
    <Reference Include="Seguridad_Geotime">
      <HintPath>..\..\..\..\Seguridad GeoTime\Seguridad_Geotime.dll</HintPath>
    </Reference>
    <Reference Include="SourceAFIS">
      <HintPath>..\..\..\..\SourceAFIS\SourceAFIS.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Connected Services\" />
    <Folder Include="Controllers\Procesos\Incidencias\" />
    <Folder Include="Dll\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="App_Data\alter_add.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\alter_modify.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\create_fks.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\create_sps.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\create_tbl.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\create_vws.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_CREATE_ADMIN_TABLES_000.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_CREATE_ADMIN_TABLES_UPGRADE.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_CREATE_PROCEDURES_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_CREATE_PROCEDURES_UPGRADE.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_CREATE_TABLES_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_INIT_ADMIN_TABLES_UPGRADE.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_INIT_TABLES.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\MSSQL_INIT_TABLES_UPGRADE.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ORA_CREATE_FUNCTIONS_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ORA_CREATE_PROCEDURES_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ORA_CREATE_SEQUENCES_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ORA_CREATE_TABLES_001.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ORA_INIT_TABLES.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>