
namespace GeotimeConnectWebApi.Models
{
    public class cEmpleadoSoftland
    {
        public string EMPLEADO { get; set; }
        public int? DETALLE_DIR_HAB { get; set; }
        public string NOMBRE { get; set; }
        public string SEXO { get; set; }
        public string? TIPO_SANGRE { get; set; }
        public string ESTADO_EMPLEADO { get; set; }
        public string ACTIVO { get; set; }
        public string? IDENTIFICACION { get; set; }
        public string? PASAPORTE { get; set; }
        public DateTime FECHA_INGRESO { get; set; }
        public DateTime? FECHA_SALIDA { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string? PUESTO { get; set; }
        public string? PLAZA { get; set; }
        public string? NOMINA { get; set; }
        public string? CENTRO_COSTO { get; set; }
        public DateTime FECHA_NACIMIENTO { get; set; }
        public string? UBICACION { get; set; }
        public string PAIS { get; set; }
        public string? ESTADO_CIVIL { get; set; }
        public short? DEPENDIENTES { get; set; }
        public string? ASEGURADO { get; set; }
        public string? CLASE_SEGURO { get; set; }
        public string? PERMISO_CONDUCIR { get; set; }
        public string? PERMISO_SALUD { get; set; }
        public string? NIT { get; set; }
        public decimal VACS_PENDIENTES { get; set; }
        public DateTime VACS_ULT_CALCULO { get; set; }
        public DateTime? FECHA_PROX_EVAL { get; set; }
        public decimal SALARIO_REFERENCIA { get; set; }
        public string? FORMA_PAGO { get; set; }
        public string? CUENTA_ENTIDAD { get; set; }
        public string? ENTIDAD_FINANCIERA { get; set; }
        public string? HORARIO { get; set; }
        public string? DIRECCION_HAB { get; set; }
        public string? DIRECCION_POSTAL { get; set; }
        public string? TELEFONO1 { get; set; }
        public string? NOTAS_TEL1 { get; set; }
        public string? TELEFONO2 { get; set; }
        public string? NOTAS_TEL2 { get; set; }
        public string? TELEFONO3 { get; set; }
        public string? NOTAS_TEL3 { get; set; }
        public byte[]? FOTOGRAFIA { get; set; }
        public string? RUBRO1 { get; set; }
        public string? RUBRO2 { get; set; }
        public string? RUBRO3 { get; set; }
        public string? RUBRO4 { get; set; }
        public string? RUBRO5 { get; set; }
        public string? RUBRO6 { get; set; }
        public string? RUBRO7 { get; set; }
        public string? RUBRO8 { get; set; }
        public string? RUBRO9 { get; set; }
        public string? RUBRO10 { get; set; }
        public string? RUBRO11 { get; set; }
        public string? RUBRO12 { get; set; }
        public string? RUBRO13 { get; set; }
        public string? RUBRO14 { get; set; }
        public string? RUBRO15 { get; set; }
        public DateTime FECHA_NO_PAGO { get; set; }
        public string? TIPO_SALARIO_AUMEN { get; set; }
        public DateTime? FECHA_ANTIG_EMP { get; set; }
        public DateTime? FECHA_ANTIG_GOB { get; set; }
        public decimal? SALARIO_DIARIO_INT { get; set; }
        public string? PRIMER_APELLIDO { get; set; }
        public string? SEGUNDO_APELLIDO { get; set; }
        public string? NOMBRE_PILA { get; set; }
        public string? E_MAIL { get; set; }
        public int? DETALLE_DIR_POSTAL { get; set; }
        public decimal VACS_ADICIONALES { get; set; }
        public string? RUBRO16 { get; set; }
        public string? RUBRO17 { get; set; }
        public string? RUBRO18 { get; set; }
        public string? RUBRO19 { get; set; }
        public string? RUBRO20 { get; set; }
        public string? RUBRO21 { get; set; }
        public string? RUBRO22 { get; set; }
        public string? RUBRO23 { get; set; }
        public string? RUBRO24 { get; set; }
        public string? RUBRO25 { get; set; }
        public decimal? SALARIOPD_LOCAL { get; set; }
        public decimal? SALARIOPD_DOLAR { get; set; }
        public decimal? SALARIOPD_NOMINA { get; set; }
        public decimal? DIAS_DISP_INCAP { get; set; }
        public string? USUARIO_CREACION { get; set; }
        public DateTime? FECHA_HORA_CREACION { get; set; }
        public string? USUARIO_ULT_MOD { get; set; }
        public DateTime? FCH_HORA_ULT_MOD { get; set; }
        public string? TIPO_CUENTA_ENTIDAD { get; set; }
        public string? CTA_ELECTRONICA { get; set; }
        public string? DIVISION_GEOGRAFICA1 { get; set; }
        public string? DIVISION_GEOGRAFICA2 { get; set; }
        public string? PAIS_DIREC { get; set; }
        public string? TIPO_SALARIO { get; set; }
        public string? BENEFICIO_COLECTIVO { get; set; }
        public int? TIPO_MEDIDAS_CERTIFICADAS { get; set; }
        public int? TIPO_NIVEL_EDUCATIVO { get; set; }
        public string? U_TDEP { get; set; }
        public string? U_COD_SUCURSAL { get; set; }
        public String? DescripcionDepartamento { get; set; }
        public String? DescripcionCentroCosto { get; set; }
        public String? DescripcionPuesto { get; set; }

    }
}
